package empresa.entity;
// Generated 09/12/2017 14:37:02 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes extends Pessoa implements java.io.Serializable {
    Pessoa c = new Pessoa();;
    private int id;

    public void setId(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }
    public Clientes() {
    }

    public Clientes(String nome, String sobrenome, String endereco, int codigo) {
        super(nome, sobrenome, endereco, codigo);
    }
        
    public void cadcli(String nome, String sobrenome, String endereco, int codigo){

            c.setNome(nome);
            c.setSobrenome(sobrenome);
            c.setEndereco(endereco);
            c.setCodigo(codigo);
    }
    
   
    @Override
   public String sucesso(){
     
       return "Cliente cadastrado com sucesso";
   }

}
